version: "3.8"
services:
  # core:
  #   image: ghcr.io/farcaller/metanotes-core:master
  server:
    image: bazel/src/backend:backend_image
    command: ["/data/db.sqlite", "0.0.0.0:55001"]
    volumes:
    - "./data:/data"
  envoy:
    image: bazel/src/envoy:envoy_image
    volumes:
    - "./src/envoy/config-dev.yaml:/config.yaml:ro"
    ports:
    - "55080:55080"
