name: build images
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Mount bazel cache
      uses: actions/cache@v2
      with: 
        path: |
          /home/runner/.cache/bazel
          dist
          node_modules
        key: bazel
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Setup yarn
      run: npm i -g yarn
    - name: Setup node dependencies
      run: yarn --frozen-lockfile
    - name: Run tests
      run: yarn test
    - name: Build container images
      run: yarn run bazel build //:container_images
